export const HotKeyMap: any = {
  OPEN_SETTINGS: {
    name: 'OPEN_SETTINGS',
    sequence: 'enter',
    action: 'keydown',
    group: 'SETTINGS',
  },
  CLOSE_SETTINGS: {
    name: 'CLOSE_SETTINGS',
    sequence: 'esc',
    action: 'keydown',
    group: 'SETTINGS',
  },
  THEME_LIGHT_SETTINGS: {
    name: 'THEME_LIGHT_SETTINGS',
    sequence: 'l',
    action: 'keydown',
    group: 'THEME',
  },
  THEME_DARK_SETTINGS: {
    name: 'THEME_DARK_SETTINGS',
    sequence: 'd',
    action: 'keydown',
    group: 'THEME',
  },
  NAVIGATE_ROUTE_UP: {
    name: 'NAVIGATE_ROUTE_UP',
    sequence: 'up',
    action: 'keydown',
    group: 'NAVIGATION',
  },
  NAVIGATE_ROUTE_DOWN: {
    name: 'NAVIGATE_ROUTE_DOWN',
    sequence: 'down',
    action: 'keydown',
    group: 'NAVIGATION',
  },
  NAVIGATE_TO_SKYBOX: {
    name: 'NAVIGATE_TO_SKYBOX',
    sequence: 'right',
    action: 'keydown',
    group: 'NAVIGATION',
  },
  NAVIGATE_TO_PHYSICS: {
    name: 'NAVIGATE_TO_PHYSICS',
    sequence: 'left',
    action: 'keydown',
    group: 'NAVIGATION',
  },
  ENGLISH_SETTINGS: {
    name: 'ENGLISH_SETTINGS',
    sequence: 'e',
    action: 'keydown',
    group: 'LANGUAGE',
  },
  BENGALI_SETTINGS: {
    name: 'BENGALI_SETTINGS',
    sequence: 'b',
    action: 'keydown',
    group: 'LANGUAGE',
  },
  TOGGLE_HELP: {
    name: 'TOGGLE_HELP',
    sequence: 'h',
    action: 'keydown',
    group: 'DRAWER',
  },
  TOGGLE_GITHUB: {
    name: 'TOGGLE_GITHUB',
    sequence: 'g',
    action: 'keydown',
    group: 'DRAWER',
  },
  TOGGLE_LINKEDIN: {
    name: 'TOGGLE_LINKEDIN',
    sequence: 'z',
    action: 'keydown',
    group: 'DRAWER',
  },
  TOGGLE_WEEBLY: {
    name: 'TOGGLE_WEEBLY',
    sequence: 'w',
    action: 'keydown',
    group: 'DRAWER',
  },
  TOGGLE_RESUME: {
    name: 'TOGGLE_RESUME',
    sequence: 'r',
    action: 'keydown',
    group: 'DRAWER',
  },
};
